# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUser1Snapdeal():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_user1Snapdeal(self):
    self.driver.get("https://www.snapdeal.com/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "inputValEnter").click()
    self.driver.find_element(By.ID, "inputValEnter").send_keys("samsung galaxy m31")
    self.driver.find_element(By.CSS_SELECTOR, ".currenthover .subDefault").click()
    self.driver.execute_script("window.scrollTo(0,57.599998474121094)")
    self.driver.find_element(By.ID, "inputValEnter").click()
    self.driver.find_element(By.ID, "inputValEnter").send_keys("samsung galaxy m21 ")
    self.driver.find_element(By.CSS_SELECTOR, ".currenthover > .subdiv").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sub-cat-list:nth-child(2) .sub-cat-name").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, "#\\36 917529682576574946 .product-title").click()
    self.vars["win8721"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win8721"])
    self.driver.find_element(By.CSS_SELECTOR, "#add-cart-button-id > .intialtext").click()
  
